interface CustomerInput {
    customerId?: number
    companyId: number
}

export const customers = (input: CustomerInput) => [
    {
        id: input.customerId || 1,
        firstName: 'Salman',
        lastName: 'Kashfy',
        phoneCode: '92',
        phoneNumber: '3322278636',
        companyId: input.companyId,
    },
    {
        id: 2,
        firstName: 'Mohammad',
        lastName: 'Amir',
        phoneCode: '92',
        phoneNumber: '3082643777',
        companyId: input.companyId,
    },
    {
        id: 3,
        firstName: 'Ahmed',
        lastName: 'Hassan',
        phoneCode: '92',
        phoneNumber: '3214567890',
        companyId: input.companyId,
    },
    {
        id: 4,
        firstName: 'Fatima',
        lastName: 'Ali',
        phoneCode: '92',
        phoneNumber: '3321234567',
        companyId: input.companyId,
    },
    {
        id: 5,
        firstName: 'Usman',
        lastName: 'Khan',
        phoneCode: '92',
        phoneNumber: '3009876543',
        companyId: input.companyId,
    },
    {
        id: 6,
        firstName: 'Ayesha',
        lastName: 'Malik',
        phoneCode: '92',
        phoneNumber: '3312345678',
        companyId: input.companyId,
    },
    {
        id: 7,
        firstName: 'Bilal',
        lastName: 'Ahmed',
        phoneCode: '92',
        phoneNumber: '3098765432',
        companyId: input.companyId,
    },
    {
        id: 8,
        firstName: 'Zainab',
        lastName: 'Raza',
        phoneCode: '92',
        phoneNumber: '3323456789',
        companyId: input.companyId,
    },
    {
        id: 9,
        firstName: 'Hassan',
        lastName: 'Iqbal',
        phoneCode: '92',
        phoneNumber: '3012345678',
        companyId: input.companyId,
    },
    {
        id: 10,
        firstName: 'Sana',
        lastName: 'Shah',
        phoneCode: '92',
        phoneNumber: '3334567890',
        companyId: input.companyId,
    },
    {
        id: 11,
        firstName: 'Omar',
        lastName: 'Butt',
        phoneCode: '92',
        phoneNumber: '3023456789',
        companyId: input.companyId,
    },
    {
        id: 12,
        firstName: 'Maryam',
        lastName: 'Rashid',
        phoneCode: '92',
        phoneNumber: '3345678901',
        companyId: input.companyId,
    },
    {
        id: 13,
        firstName: 'Tariq',
        lastName: 'Nawaz',
        phoneCode: '92',
        phoneNumber: '3034567890',
        companyId: input.companyId,
    },
    {
        id: 14,
        firstName: 'Hina',
        lastName: 'Qureshi',
        phoneCode: '92',
        phoneNumber: '3356789012',
        companyId: input.companyId,
    },
    {
        id: 15,
        firstName: 'Kamran',
        lastName: 'Sheikh',
        phoneCode: '92',
        phoneNumber: '3045678901',
        companyId: input.companyId,
    },
    {
        id: 16,
        firstName: 'Nida',
        lastName: 'Abbas',
        phoneCode: '92',
        phoneNumber: '3367890123',
        companyId: input.companyId,
    }
]
