interface CustomerInput {
    customerId?: number
    companyId: number
}

export const customers = (input: CustomerInput) => [
    {
        id: input.customerId || 1,
        firstName: 'Salman',
        lastName: 'Kashfy',
        phoneCode: '92',
        phoneNumber: '3322278636',
        companyId: input.companyId,
    },
    {
        id: 2,
        firstName: 'Mohammad',
        lastName: 'Amir',
        phoneCode: '92',
        phoneNumber: '3082643777',
        companyId: input.companyId,
    },
    {
        id: 3,
        firstName: 'Ahmed',
        lastName: 'Hassan',
        phoneCode: '92',
        phoneNumber: '3214567890',
        companyId: input.companyId,
    },
    {
        id: 4,
        firstName: 'Fatima',
        lastName: 'Ali',
        phoneCode: '92',
        phoneNumber: '3321234567',
        companyId: input.companyId,
    },
    {
        id: 5,
        firstName: 'Usman',
        lastName: 'Khan',
        phoneCode: '92',
        phoneNumber: '3009876543',
        companyId: input.companyId,
    },
    {
        id: 6,
        firstName: 'Ayesha',
        lastName: 'Malik',
        phoneCode: '92',
        phoneNumber: '3312345678',
        companyId: input.companyId,
    },
    {
        id: 7,
        firstName: 'Bilal',
        lastName: 'Ahmed',
        phoneCode: '92',
        phoneNumber: '3098765432',
        companyId: input.companyId,
    },
    {
        id: 8,
        firstName: 'Zainab',
        lastName: 'Raza',
        phoneCode: '92',
        phoneNumber: '3323456789',
        companyId: input.companyId,
    },
    {
        id: 9,
        firstName: 'Hassan',
        lastName: 'Iqbal',
        phoneCode: '92',
        phoneNumber: '3012345678',
        companyId: input.companyId,
    },
    {
        id: 10,
        firstName: 'Sana',
        lastName: 'Shah',
        phoneCode: '92',
        phoneNumber: '3334567890',
        companyId: input.companyId,
    },
    {
        id: 11,
        firstName: 'Omar',
        lastName: 'Butt',
        phoneCode: '92',
        phoneNumber: '3023456789',
        companyId: input.companyId,
    },
    {
        id: 12,
        firstName: 'Maryam',
        lastName: 'Rashid',
        phoneCode: '92',
        phoneNumber: '3345678901',
        companyId: input.companyId,
    },
    {
        id: 13,
        firstName: 'Tariq',
        lastName: 'Nawaz',
        phoneCode: '92',
        phoneNumber: '3034567890',
        companyId: input.companyId,
    },
    {
        id: 14,
        firstName: 'Hina',
        lastName: 'Qureshi',
        phoneCode: '92',
        phoneNumber: '3356789012',
        companyId: input.companyId,
    },
    {
        id: 15,
        firstName: 'Kamran',
        lastName: 'Sheikh',
        phoneCode: '92',
        phoneNumber: '3045678901',
        companyId: input.companyId,
    },
    {
        id: 16,
        firstName: 'Nida',
        lastName: 'Abbas',
        phoneCode: '92',
        phoneNumber: '3367890123',
        companyId: input.companyId,
    },
    {
        id: 17,
        firstName: 'Ali',
        lastName: 'Hussain',
        phoneCode: '92',
        phoneNumber: '3378901234',
        companyId: input.companyId,
    },
    {
        id: 18,
        firstName: 'Rabia',
        lastName: 'Khan',
        phoneCode: '92',
        phoneNumber: '3056789012',
        companyId: input.companyId,
    },
    {
        id: 19,
        firstName: 'Faisal',
        lastName: 'Mehmood',
        phoneCode: '92',
        phoneNumber: '3389012345',
        companyId: input.companyId,
    },
    {
        id: 20,
        firstName: 'Saima',
        lastName: 'Yousuf',
        phoneCode: '92',
        phoneNumber: '3067890123',
        companyId: input.companyId,
    },
    {
        id: 21,
        firstName: 'Waseem',
        lastName: 'Akram',
        phoneCode: '92',
        phoneNumber: '3390123456',
        companyId: input.companyId,
    },
    {
        id: 22,
        firstName: 'Amina',
        lastName: 'Siddiqui',
        phoneCode: '92',
        phoneNumber: '3078901234',
        companyId: input.companyId,
    },
    {
        id: 23,
        firstName: 'Imran',
        lastName: 'Baig',
        phoneCode: '92',
        phoneNumber: '3301234567',
        companyId: input.companyId,
    },
    {
        id: 24,
        firstName: 'Sara',
        lastName: 'Mirza',
        phoneCode: '92',
        phoneNumber: '3089012345',
        companyId: input.companyId,
    },
    {
        id: 25,
        firstName: 'Nadeem',
        lastName: 'Chaudhry',
        phoneCode: '92',
        phoneNumber: '3312345678',
        companyId: input.companyId,
    },
    {
        id: 26,
        firstName: 'Aisha',
        lastName: 'Farooq',
        phoneCode: '92',
        phoneNumber: '3090123456',
        companyId: input.companyId,
    },
    {
        id: 27,
        firstName: 'Rashid',
        lastName: 'Malik',
        phoneCode: '92',
        phoneNumber: '3323456789',
        companyId: input.companyId,
    },
    {
        id: 28,
        firstName: 'Zara',
        lastName: 'Ahmed',
        phoneCode: '92',
        phoneNumber: '3001234567',
        companyId: input.companyId,
    },
    {
        id: 29,
        firstName: 'Khalid',
        lastName: 'Rana',
        phoneCode: '92',
        phoneNumber: '3334567890',
        companyId: input.companyId,
    },
    {
        id: 30,
        firstName: 'Layla',
        lastName: 'Hashmi',
        phoneCode: '92',
        phoneNumber: '3012345678',
        companyId: input.companyId,
    },
    {
        id: 31,
        firstName: 'Asad',
        lastName: 'Qureshi',
        phoneCode: '92',
        phoneNumber: '3345678901',
        companyId: input.companyId,
    },
    {
        id: 32,
        firstName: 'Hira',
        lastName: 'Nawaz',
        phoneCode: '92',
        phoneNumber: '3023456789',
        companyId: input.companyId,
    },
    {
        id: 33,
        firstName: 'Zubair',
        lastName: 'Sheikh',
        phoneCode: '92',
        phoneNumber: '3356789012',
        companyId: input.companyId,
    },
    {
        id: 34,
        firstName: 'Mariam',
        lastName: 'Butt',
        phoneCode: '92',
        phoneNumber: '3034567890',
        companyId: input.companyId,
    },
    {
        id: 35,
        firstName: 'Saad',
        lastName: 'Iqbal',
        phoneCode: '92',
        phoneNumber: '3367890123',
        companyId: input.companyId,
    },
    {
        id: 36,
        firstName: 'Ayesha',
        lastName: 'Rashid',
        phoneCode: '92',
        phoneNumber: '3045678901',
        companyId: input.companyId,
    },
    {
        id: 37,
        firstName: 'Hamza',
        lastName: 'Abbas',
        phoneCode: '92',
        phoneNumber: '3378901234',
        companyId: input.companyId,
    },
    {
        id: 38,
        firstName: 'Noor',
        lastName: 'Hassan',
        phoneCode: '92',
        phoneNumber: '3056789012',
        companyId: input.companyId,
    },
    {
        id: 39,
        firstName: 'Tahir',
        lastName: 'Ali',
        phoneCode: '92',
        phoneNumber: '3389012345',
        companyId: input.companyId,
    },
    {
        id: 40,
        firstName: 'Hafsa',
        lastName: 'Khan',
        phoneCode: '92',
        phoneNumber: '3067890123',
        companyId: input.companyId,
    },
    {
        id: 41,
        firstName: 'Yasir',
        lastName: 'Malik',
        phoneCode: '92',
        phoneNumber: '3390123456',
        companyId: input.companyId,
    },
    {
        id: 42,
        firstName: 'Saba',
        lastName: 'Ahmed',
        phoneCode: '92',
        phoneNumber: '3078901234',
        companyId: input.companyId,
    },
    {
        id: 43,
        firstName: 'Adnan',
        lastName: 'Raza',
        phoneCode: '92',
        phoneNumber: '3301234567',
        companyId: input.companyId,
    },
    {
        id: 44,
        firstName: 'Iqra',
        lastName: 'Shah',
        phoneCode: '92',
        phoneNumber: '3089012345',
        companyId: input.companyId,
    },
    {
        id: 45,
        firstName: 'Zain',
        lastName: 'Butt',
        phoneCode: '92',
        phoneNumber: '3312345678',
        companyId: input.companyId,
    },
    {
        id: 46,
        firstName: 'Areeba',
        lastName: 'Qureshi',
        phoneCode: '92',
        phoneNumber: '3090123456',
        companyId: input.companyId,
    },
    {
        id: 47,
        firstName: 'Danish',
        lastName: 'Sheikh',
        phoneCode: '92',
        phoneNumber: '3323456789',
        companyId: input.companyId,
    },
    {
        id: 48,
        firstName: 'Sana',
        lastName: 'Iqbal',
        phoneCode: '92',
        phoneNumber: '3002345678',
        companyId: input.companyId,
    }
]
