import {PERMISSIONS} from "./index";

export const ADMIN_PERMISSIONS = [
    PERMISSIONS.CATEGORY.VIEW.ID,
    PERMISSIONS.CATEGORY.UPDATE.ID,
    PERMISSIONS.CATEGORY.DELETE.ID,

    PERMISSIONS.TABLE.CREATE.ID,
    PERMISSIONS.TABLE.UPDATE.ID,
    PERMISSIONS.TABLE.VIEW.ID,
    PERMISSIONS.TABLE.DELETE.ID,

    PERMISSIONS.SHIFT.UPSERT.ID,
    PERMISSIONS.SHIFT.VIEW.ID,
    PERMISSIONS.SHIFT.DELETE.ID,

    PERMISSIONS.CUSTOMER.CREATE.ID,
    PERMISSIONS.CUSTOMER.UPDATE.ID,
    PERMISSIONS.CUSTOMER.VIEW.ID,
    PERMISSIONS.CUSTOMER.DELETE.ID,

    PERMISSIONS.TABLE_SESSION.CREATE.ID,
    PERMISSIONS.TABLE_SESSION.UPDATE.ID,
    PERMISSIONS.TABLE_SESSION.VIEW.ID,
    PERMISSIONS.TABLE_SESSION.DELETE.ID,

    PERMISSIONS.PAYMENT.CREATE.ID,
    PERMISSIONS.PAYMENT.UPDATE.ID,
    PERMISSIONS.PAYMENT.VIEW.ID,
    PERMISSIONS.PAYMENT.DELETE.ID,
]