import {PERMISSIONS} from "./index";

export const EMPLOYEE_PERMISSIONS = [
    PERMISSIONS.TABLE.VIEW.ID,
    PERMISSIONS.SHIFT.VIEW.ID,
    PERMISSIONS.CUSTOMER.UPSERT.ID,
    PERMISSIONS.CUSTOMER.DELETE.ID,
    PERMISSIONS.CUSTOMER.VIEW.ID,
    PERMISSIONS.TABLE_SESSION.UPSERT.ID,
    PERMISSIONS.TABLE_SESSION.VIEW.ID,
    PERMISSIONS.PAYMENT.UPSERT.ID,
    PERMISSIONS.PAYMENT.VIEW.ID,
]