import {PERMISSIONS} from "./index";

export const EMPLOYEE_PERMISSIONS = [
    PERMISSIONS.CATEGORY.VIEW.ID,
    PERMISSIONS.CATEGORY.UPSERT.ID,
    PERMISSIONS.CATEGORY.DELETE.ID,

    PERMISSIONS.TABLE.UPSERT.ID,
    PERMISSIONS.TABLE.VIEW.ID,
    PERMISSIONS.TABLE.DELETE.ID,

    PERMISSIONS.SHIFT.UPSERT.ID,
    PERMISSIONS.SHIFT.VIEW.ID,
    PERMISSIONS.SHIFT.DELETE.ID,

    PERMISSIONS.CUSTOMER.UPSERT.ID,
    PERMISSIONS.CUSTOMER.VIEW.ID,
    PERMISSIONS.CUSTOMER.DELETE.ID,

    PERMISSIONS.TABLE_SESSION.UPSERT.ID,
    PERMISSIONS.TABLE_SESSION.VIEW.ID,
    PERMISSIONS.TABLE_SESSION.DELETE.ID,

    PERMISSIONS.PAYMENT.UPSERT.ID,
    PERMISSIONS.PAYMENT.VIEW.ID,
    PERMISSIONS.PAYMENT.DELETE.ID,

    // PERMISSIONS.PAYMENT.VIEW.ID,
]