import {PERMISSIONS} from "./index";

export const EMPLOYEE_PERMISSIONS = [
    PERMISSIONS.TABLE.VIEW.ID,
    PERMISSIONS.SHIFT.VIEW.ID,
    PERMISSIONS.CUSTOMER.CREATE.ID,
    PERMISSIONS.CUSTOMER.UPDATE.ID,
    PERMISSIONS.CUSTOMER.DELETE.ID,
    PERMISSIONS.CUSTOMER.VIEW.ID,
    PERMISSIONS.TABLE_SESSION.CREATE.ID,
    PERMISSIONS.TABLE_SESSION.UPDATE.ID,
    PERMISSIONS.TABLE_SESSION.VIEW.ID,
    PERMISSIONS.PAYMENT.CREATE.ID,
    PERMISSIONS.PAYMENT.VIEW.ID,
]