export const UserError = {
  DUPLICATE_USERNAME: 'DUPLICATE_USERNAME',
  INVALID_ID: 'INVALID_ID',
  DUPLICATE_CONTACT_NUMBER: 'DUPLICATE_CONTACT_NUMBER',
  ROLES_REQUIRED: 'ROLES_REQUIRED',
  INVALID_CONTACT_NUMBER: 'INVALID_CONTACT_NUMBER',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  NOT_ALLOWED: 'NOT_ALLOWED',
  INVALID_FILE_EXTENSION: 'INVALID_FILE_EXTENSION',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
};